// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 82805ebdf0b5ff0d "Apptics (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { routes } from "../chunks/chunk-VAWW4KIH.js";

// virtual:elements/automate-billing
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/oOdOVwjTuNbYwvBNUXcx/CeJNXtQ5tbREoUo0MnML/bzJL5MtLc.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ImageWithFX = withFX(Image);
var MotionDivWithFX = withFX(motion.div);
var serializationHash = "framer-nQnzs";
var variantClassNames = {
	x0omn_QO1: "framer-v-872h4p",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	delay: 0,
	duration: 16,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var animation1 = {
	opacity: 1,
	rotate: -360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition3 = {
	delay: 0,
	duration: 18,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var transformTemplate2 = (_, t) => `translateY(-50%) ${t}`;
var transition4 = {
	delay: 0,
	duration: 20,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "x0omn_QO1",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-872h4p",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"x0omn_QO1"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							...style,
						}}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 540,
								intrinsicWidth: 560,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 0,
								),
								pixelHeight: 810,
								pixelWidth: 840,
								sizes: componentViewport?.width || "100vw",
								src: "https://framerusercontent.com/images/7hrZZohyroMK4oOST3k34r9mHuo.png",
								srcSet:
									"https://framerusercontent.com/images/7hrZZohyroMK4oOST3k34r9mHuo.png?scale-down-to=512 512w,https://framerusercontent.com/images/7hrZZohyroMK4oOST3k34r9mHuo.png 840w",
							}}
							className={"framer-fyb8mf"}
							data-framer-name={"B1 circle"}
							layoutDependency={layoutDependency}
							layoutId={"vsDSJ2qA_"}
						/>
						<MotionDivWithFX
							__framer__loop={animation}
							__framer__loopEffectEnabled={true}
							__framer__loopPauseOffscreen={true}
							__framer__loopRepeatDelay={0}
							__framer__loopRepeatType={"loop"}
							__framer__loopTransition={transition2}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-1qdv123"}
							data-framer-name={"Ring 1"}
							layoutDependency={layoutDependency}
							layoutId={"j0Z8aUfVZ"}
							style={{
								borderBottomLeftRadius: "50%",
								borderBottomRightRadius: "50%",
								borderTopLeftRadius: "50%",
								borderTopRightRadius: "50%",
							}}
							transformTemplate={transformTemplate1}
						>
							<ImageWithFX
								__framer__loop={animation1}
								__framer__loopEffectEnabled={true}
								__framer__loopPauseOffscreen={true}
								__framer__loopRepeatDelay={0}
								__framer__loopRepeatType={"loop"}
								__framer__loopTransition={transition2}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											((componentViewport?.height || 405) * 0.5012345679012348 -
												80) +
											-13,
									),
									pixelHeight: 111,
									pixelWidth: 111,
									src: "https://framerusercontent.com/images/VPPoV8M4C8gFeJjq3eui0COmO8.png",
								}}
								className={"framer-1uw0ug5"}
								data-framer-name={"Logo"}
								layoutDependency={layoutDependency}
								layoutId={"eMfBKSHea"}
								style={{
									borderBottomLeftRadius: 99,
									borderBottomRightRadius: 99,
									borderTopLeftRadius: 99,
									borderTopRightRadius: 99,
									boxShadow:
										"0px 1px 1px 0px rgba(35, 28, 95, 0.07), 0px 2px 2px 0px rgba(35, 28, 95, 0.06), 0px 5px 3px 0px rgba(35, 28, 95, 0.03)",
								}}
							/>
							<ImageWithFX
								__framer__loop={animation1}
								__framer__loopEffectEnabled={true}
								__framer__loopPauseOffscreen={true}
								__framer__loopRepeatDelay={0}
								__framer__loopRepeatType={"loop"}
								__framer__loopTransition={transition2}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											((componentViewport?.height || 405) * 0.5012345679012348 -
												80) +
											160 -
											78,
									),
									pixelHeight: 111,
									pixelWidth: 111,
									src: "https://framerusercontent.com/images/9USkc2LGfg7FCFanvh58MOo0M.png",
								}}
								className={"framer-15lsj3i"}
								data-framer-name={"Logo"}
								layoutDependency={layoutDependency}
								layoutId={"IbPh65bFq"}
								style={{
									borderBottomLeftRadius: 99,
									borderBottomRightRadius: 99,
									borderTopLeftRadius: 99,
									borderTopRightRadius: 99,
									boxShadow:
										"0px 1px 1px 0px rgba(35, 28, 95, 0.07), 0px 2px 2px 0px rgba(35, 28, 95, 0.06), 0px 5px 3px 0px rgba(35, 28, 95, 0.03)",
								}}
							/>
						</MotionDivWithFX>
						<MotionDivWithFX
							__framer__loop={animation}
							__framer__loopEffectEnabled={true}
							__framer__loopPauseOffscreen={true}
							__framer__loopRepeatDelay={0}
							__framer__loopRepeatType={"loop"}
							__framer__loopTransition={transition3}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-upaj10"}
							data-framer-name={"Ring 2"}
							layoutDependency={layoutDependency}
							layoutId={"JErBcLMze"}
							style={{
								borderBottomLeftRadius: "50%",
								borderBottomRightRadius: "50%",
								borderTopLeftRadius: "50%",
								borderTopRightRadius: "50%",
							}}
							transformTemplate={transformTemplate1}
						>
							<ImageWithFX
								__framer__loop={animation1}
								__framer__loopEffectEnabled={true}
								__framer__loopPauseOffscreen={true}
								__framer__loopRepeatDelay={0}
								__framer__loopRepeatType={"loop"}
								__framer__loopTransition={transition3}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											((componentViewport?.height || 405) * 0.5012345679012348 -
												117.5) +
											79.5,
									),
									pixelHeight: 111,
									pixelWidth: 111,
									src: "https://framerusercontent.com/images/ZYmikZLXIRT5yhrnMi1VEqkpQps.png",
								}}
								className={"framer-1v9yq2z"}
								data-framer-name={"Logo"}
								layoutDependency={layoutDependency}
								layoutId={"DOqtljXlw"}
								style={{
									borderBottomLeftRadius: 99,
									borderBottomRightRadius: 99,
									borderTopLeftRadius: 99,
									borderTopRightRadius: 99,
									boxShadow:
										"0px 1px 1px 0px rgba(35, 28, 95, 0.07), 0px 2px 2px 0px rgba(35, 28, 95, 0.06), 0px 5px 3px 0px rgba(35, 28, 95, 0.03)",
								}}
								transformTemplate={transformTemplate2}
							/>
							<ImageWithFX
								__framer__loop={animation1}
								__framer__loopEffectEnabled={true}
								__framer__loopPauseOffscreen={true}
								__framer__loopRepeatDelay={0}
								__framer__loopRepeatType={"loop"}
								__framer__loopTransition={transition3}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											((componentViewport?.height || 405) * 0.5012345679012348 -
												117.5) +
											-11,
									),
									pixelHeight: 110,
									pixelWidth: 111,
									src: "https://framerusercontent.com/images/3YJuO3fvRPiWzfughBHPk5a4CB0.png",
								}}
								className={"framer-1ae58cz"}
								data-framer-name={"Logo"}
								layoutDependency={layoutDependency}
								layoutId={"k3E9m7Qqm"}
								style={{
									borderBottomLeftRadius: 99,
									borderBottomRightRadius: 99,
									borderTopLeftRadius: 99,
									borderTopRightRadius: 99,
									boxShadow:
										"0px 1px 1px 0px rgba(35, 28, 95, 0.07), 0px 2px 2px 0px rgba(35, 28, 95, 0.06), 0px 5px 3px 0px rgba(35, 28, 95, 0.03)",
								}}
							/>
							<ImageWithFX
								__framer__loop={animation1}
								__framer__loopEffectEnabled={true}
								__framer__loopPauseOffscreen={true}
								__framer__loopRepeatDelay={0}
								__framer__loopRepeatType={"loop"}
								__framer__loopTransition={transition3}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											((componentViewport?.height || 405) * 0.5012345679012348 -
												117.5) +
											235 -
											30,
									),
									pixelHeight: 111,
									pixelWidth: 111,
									src: "https://framerusercontent.com/images/YVZIOWdCKuvoQTakBvNRTK1iSC8.png",
								}}
								className={"framer-z3d4p6"}
								data-framer-name={"Logo"}
								layoutDependency={layoutDependency}
								layoutId={"B6bJso4IZ"}
								style={{
									borderBottomLeftRadius: 99,
									borderBottomRightRadius: 99,
									borderTopLeftRadius: 99,
									borderTopRightRadius: 99,
									boxShadow:
										"0px 1px 1px 0px rgba(35, 28, 95, 0.07), 0px 2px 2px 0px rgba(35, 28, 95, 0.06), 0px 5px 3px 0px rgba(35, 28, 95, 0.03)",
								}}
							/>
						</MotionDivWithFX>
						<MotionDivWithFX
							__framer__loop={animation}
							__framer__loopEffectEnabled={true}
							__framer__loopPauseOffscreen={true}
							__framer__loopRepeatDelay={0}
							__framer__loopRepeatType={"loop"}
							__framer__loopTransition={transition4}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-gn0hhw"}
							data-framer-name={"Ring 3"}
							layoutDependency={layoutDependency}
							layoutId={"kHrFfUCWi"}
							style={{
								borderBottomLeftRadius: "50%",
								borderBottomRightRadius: "50%",
								borderTopLeftRadius: "50%",
								borderTopRightRadius: "50%",
							}}
							transformTemplate={transformTemplate1}
						>
							<ImageWithFX
								__framer__loop={animation1}
								__framer__loopEffectEnabled={true}
								__framer__loopPauseOffscreen={true}
								__framer__loopRepeatDelay={0}
								__framer__loopRepeatType={"loop"}
								__framer__loopTransition={transition4}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											((componentViewport?.height || 405) * 0.5012345679012348 -
												160) +
											-5,
									),
									pixelHeight: 110,
									pixelWidth: 110,
									src: "https://framerusercontent.com/images/XkPsfTQFKlCLbfxK6EVpY2mtE.png",
								}}
								className={"framer-1f0cs8z"}
								data-framer-name={"Logo"}
								layoutDependency={layoutDependency}
								layoutId={"UOM4c9pyr"}
								style={{
									borderBottomLeftRadius: 99,
									borderBottomRightRadius: 99,
									borderTopLeftRadius: 99,
									borderTopRightRadius: 99,
									boxShadow:
										"0px 1px 1px 0px rgba(35, 28, 95, 0.07), 0px 2px 2px 0px rgba(35, 28, 95, 0.06), 0px 5px 3px 0px rgba(35, 28, 95, 0.03)",
								}}
							/>
							<ImageWithFX
								__framer__loop={animation1}
								__framer__loopEffectEnabled={true}
								__framer__loopPauseOffscreen={true}
								__framer__loopRepeatDelay={0}
								__framer__loopRepeatType={"loop"}
								__framer__loopTransition={transition4}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											((componentViewport?.height || 405) * 0.5012345679012348 -
												160) +
											320 -
											70,
									),
									pixelHeight: 111,
									pixelWidth: 111,
									src: "https://framerusercontent.com/images/yYfFN3RKcMU46DfLby9xWLlKY.png",
								}}
								className={"framer-stroxa"}
								data-framer-name={"Logo"}
								layoutDependency={layoutDependency}
								layoutId={"txsI5cf5E"}
								style={{
									borderBottomLeftRadius: 99,
									borderBottomRightRadius: 99,
									borderTopLeftRadius: 99,
									borderTopRightRadius: 99,
									boxShadow:
										"0px 1px 1px 0px rgba(35, 28, 95, 0.07), 0px 2px 2px 0px rgba(35, 28, 95, 0.06), 0px 5px 3px 0px rgba(35, 28, 95, 0.03)",
								}}
							/>
							<ImageWithFX
								__framer__loop={animation1}
								__framer__loopEffectEnabled={true}
								__framer__loopPauseOffscreen={true}
								__framer__loopRepeatDelay={0}
								__framer__loopRepeatType={"loop"}
								__framer__loopTransition={transition4}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											((componentViewport?.height || 405) * 0.5012345679012348 -
												160) +
											320 -
											87,
									),
									pixelHeight: 111,
									pixelWidth: 110,
									src: "https://framerusercontent.com/images/25TCe7CeEBbvAkYlKFGm19y6c.png",
								}}
								className={"framer-15597vo"}
								data-framer-name={"Logo"}
								layoutDependency={layoutDependency}
								layoutId={"U0VpzzcPg"}
								style={{
									borderBottomLeftRadius: 99,
									borderBottomRightRadius: 99,
									borderTopLeftRadius: 99,
									borderTopRightRadius: 99,
									boxShadow:
										"0px 1px 1px 0px rgba(35, 28, 95, 0.07), 0px 2px 2px 0px rgba(35, 28, 95, 0.06), 0px 5px 3px 0px rgba(35, 28, 95, 0.03)",
								}}
							/>
							<ImageWithFX
								__framer__loop={animation1}
								__framer__loopEffectEnabled={true}
								__framer__loopPauseOffscreen={true}
								__framer__loopRepeatDelay={0}
								__framer__loopRepeatType={"loop"}
								__framer__loopTransition={transition4}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											((componentViewport?.height || 405) * 0.5012345679012348 -
												160) +
											80,
									),
									pixelHeight: 111,
									pixelWidth: 111,
									src: "https://framerusercontent.com/images/cZL0cHBqu58mebB7hHSU5UJ6VKY.png",
								}}
								className={"framer-2b18dj"}
								data-framer-name={"Logo"}
								layoutDependency={layoutDependency}
								layoutId={"KHSHv_I_b"}
								style={{
									borderBottomLeftRadius: 99,
									borderBottomRightRadius: 99,
									borderTopLeftRadius: 99,
									borderTopRightRadius: 99,
									boxShadow:
										"0px 1px 1px 0px rgba(35, 28, 95, 0.07), 0px 2px 2px 0px rgba(35, 28, 95, 0.06), 0px 5px 3px 0px rgba(35, 28, 95, 0.03)",
								}}
							/>
						</MotionDivWithFX>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-nQnzs.framer-a7a22p, .framer-nQnzs .framer-a7a22p { display: block; }",
	".framer-nQnzs.framer-872h4p { height: 405px; overflow: hidden; position: relative; width: 420px; }",
	".framer-nQnzs .framer-fyb8mf { aspect-ratio: 1.037037037037037 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 405px); left: 0px; overflow: visible; position: absolute; top: 0px; width: 100%; }",
	".framer-nQnzs .framer-1qdv123 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 160px); left: 50%; overflow: visible; position: absolute; top: 50%; width: 160px; }",
	".framer-nQnzs .framer-1uw0ug5 { aspect-ratio: 1 / 1; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 55px); left: 8px; overflow: visible; position: absolute; top: -13px; width: 55px; }",
	".framer-nQnzs .framer-15lsj3i { aspect-ratio: 1 / 1; bottom: 23px; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 55px); overflow: visible; position: absolute; right: -18px; width: 55px; }",
	".framer-nQnzs .framer-upaj10 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 235px); left: 50%; overflow: visible; position: absolute; top: 50%; width: 235px; }",
	".framer-nQnzs .framer-1v9yq2z { aspect-ratio: 1 / 1; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 55px); left: -27px; overflow: visible; position: absolute; top: 46%; width: 55px; }",
	".framer-nQnzs .framer-1ae58cz { aspect-ratio: 1 / 1; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 55px); left: 148px; overflow: visible; position: absolute; top: -11px; width: 55px; }",
	".framer-nQnzs .framer-z3d4p6 { aspect-ratio: 1 / 1; bottom: -25px; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 55px); left: 73px; overflow: visible; position: absolute; width: 55px; }",
	".framer-nQnzs .framer-gn0hhw { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 320px); left: 50%; overflow: visible; position: absolute; top: 50%; width: 320px; }",
	".framer-nQnzs .framer-1f0cs8z { aspect-ratio: 1 / 1; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 55px); left: 57px; overflow: visible; position: absolute; top: -5px; width: 55px; }",
	".framer-nQnzs .framer-stroxa { aspect-ratio: 1 / 1; bottom: 15px; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 55px); left: 240px; overflow: visible; position: absolute; width: 55px; }",
	".framer-nQnzs .framer-15597vo { aspect-ratio: 1 / 1; bottom: 32px; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 55px); left: 0px; overflow: visible; position: absolute; width: 55px; }",
	".framer-nQnzs .framer-2b18dj { aspect-ratio: 1 / 1; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 55px); overflow: visible; position: absolute; right: -18px; top: 80px; width: 55px; }",
];
var FramerbzJL5MtLc = withCSS(Component, css, "framer-nQnzs");
var stdin_default = FramerbzJL5MtLc;
FramerbzJL5MtLc.displayName = "Elements/Automate billing";
FramerbzJL5MtLc.defaultProps = {
	height: 405,
	width: 420,
};
addFonts(
	FramerbzJL5MtLc,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:elements/automate-billing
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"82805ebdf0b5ff0d009fec4f748e6f81207f7e9b7f138594ce37e1d247ff0150"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AutomateBillingFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"82805ebdf0b5ff0d009fec4f748e6f81207f7e9b7f138594ce37e1d247ff0150"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var automate_billing_default = ComponentWithRoot;
export { automate_billing_default as default };
